### ISSUE TITLE
Misspelled "orchestrate"

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/gulp-uf-bundle-assets#35]
For example, `BundleOrchastrator` should be `BundleOrchestrator`.

**Comment by Silic0nS0ldier** [comment]
Symbol is exported under the `default` alias, so this change can be made in a patch level release.

**Comment by Silic0nS0ldier** [comment]
Fixed under develop branch, `cspell` has been added to CI to do automated spell checks.
